"""initial migration

Revision ID: 883d2f32e078
Revises: 
Create Date: 2018-09-17 14:38:58.062872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883d2f32e078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
